### ISSUE TITLE
Testing GL3/GLES/Windows binaries

### ISSUE THREAD

**Issue by Aqua1ung** [aurgatech/linux-binaries#1]
I tested the Linux binaries you posted, as well as the Windows exe (in Wine),  and I am posting below three screen recordings. You will notice the following:

1. The native Linux binaries produce _extreme (100%) CPU utilization_, while the AURGAViewerEXE-on-Wine does _not_;
2. The cursor can**not** be controlled with any of the native Linux binaries; the AURGAViewerEXE-on-Wine application, on the other hand, _does_ allow mouse control;
3. All these applications suffer from the "disappearing mouse cursor" phenomenon: the cursor disappears (most of the time) when dragged over the AURGAViewer window.

[GL3_binary.webm](https://github.com/aurgatech/linux-binaries/assets/12104779/ad6ab08f-130e-4a64-9bdf-f69be091c473)
[GLES_binary.webm](https://github.com/aurgatech/linux-binaries/assets/12104779/8ee6b2a5-4376-4303-b5e0-c16e75e6f114)
[Windows_binary_Wine.webm](https://github.com/aurgatech/linux-binaries/assets/12104779/7058dc44-1cfe-4ded-9fb2-867c9db7a60e)

**Comment by aurgatech** [comment]
Thanks for your feedback. For point 2 & 3 with the linux binaries. Please create a udev rule to allow the app to access mouse/keyboard events in userspace.
  `$sudo nano /etc/udev/rules.d/99-input-permissions.rules`
  
  Paste the line in 99-input-permissions.rules
  `KERNEL=="event*", SUBSYSTEM=="input", MODE="0666", GROUP="input"`

  Apply the rules:
  `$sudo udevadm control --reload-rules && sudo udevadm trigger`

**Comment by Aqua1ung** [comment]
No change whatsoever:

[GL3.webm](https://github.com/aurgatech/linux-binaries/assets/12104779/9cc23b94-c3a8-4f60-b24d-db9c48b7e6a5)

[GLES.webm](https://github.com/aurgatech/linux-binaries/assets/12104779/9c2260be-c80c-4803-992b-96dfc0ca3126)

**Comment by ppc52776** [comment]
Same here, any update ?

**Comment by Aqua1ung** [comment]
> Same here, any update ?

Wine does it for me just fine. I am guessing AURGA manufacturers won't bother with ClearLinux, so I'd suggest you try Wine. Works like a charm.

**Comment by Aqua1ung** [comment]
Obsolete. Closing.
