### ISSUE TITLE
Wrong tar.xz filename for 2.0.0.5?

### ISSUE THREAD

**Issue by Aqua1ung** [aurgatech/linux-binaries#13]
[Release page for v2.0.0.5](https://github.com/aurgatech/linux-binaries/releases/tag/v2.0.0.5) shows `AURGA.Viewer-2.0.0.4_x86_64.tar.xz`. Is that correct? Shouldn't it be `AURGA.Viewer-2.0.0.5_x86_64.tar.xz`?

**Comment by aurgatech** [comment]
Thank you. Yes, the name was wrong. I've corrected it. :)
