### ISSUE TITLE
Account login data does not persist

### ISSUE THREAD

**Issue by Aqua1ung** [aurgatech/linux-binaries#9]
Every time I launch `aurgav`, I need to fill out the account login data, which is very annoying. Can you make it so these settings are persisted somewhere on the hard drive?

![Screenshot from 2024-08-31 13-17-06](https://github.com/user-attachments/assets/e4041d82-e570-4647-aa16-b9a46da1d2e6)

**Comment by aurgatech** [comment]
Please check v2.0.0.4
